= Besprechungsprotokoll
Christian Donnabauer
1.0, 2020-08-29
ifndef::imagesdir[:imagesdir: images]
:icons: font
:toc: left

.Organisatorisches
|===

|Teilnehmer |C. Donnabauer, T. Stuetz
|Ort|Discord
|Datum - Uhrzeit| 29.08.2020 - 10:00
|Dauer| 1:30h
|===

== Besprochene Themen

* System Architektur
* nächsten Schritte|https://donnabauerc.github.io/LeoCodeDocs/2020_08_07[07.08.2020]

== Vereinbarungen und Entscheidungen

* System Architektur mit Plant UML
* Umstieg auf Jenkins nach evtl. Lösung von GraalVM
* Skizzen der Website mit Bleistift
* ansehen des Videos https://www.youtube.com/watch?v=yA9TocpMthI
* erstellen einer Jenkins Pipeline -> Zugriff per Rest oder Hook
* Tägliche Pushes und Feature Branches

[plantuml,sysarch,png]
----
@startuml
package "Jenkins" {
  [ProjectUnderTest]
}
package "local git-repo" as git {
  [ProjectUnderTestRepo]
}
node "LeoCodeJavaTesting" <<quarkus>> as javatesting
node "LeoBackend" <<quarkus>> as backend
node "LeoGui" <<nodeJS>> as guiserver
node "Browser" <<angular>> as browser
() GuiApi
() BackendApi
() TestApi

javatesting -right-> git
[ProjectUnderTest] -right-> [ProjectUnderTestRepo]
javatesting -down-> TestApi
backend .up.> TestApi : use
backend -down-> BackendApi
guiserver .up.> BackendApi : use
guiserver -down-> GuiApi
browser .up.> GuiApi : use

'note right of javatesting : mvn test

@enduml
----

== Optionen

=== Option 1: Testen als Prozess

* Die Tests werden auf der Shell mit mvn durchgeführt.
* Probleme
Vermischung von Produktivsystem und ProjectUnderTest (gleiches Environment)
Ev. durch Verwendung von Graal können Tests nicht durchgeführt werden

=== Option 2: Auslagern in  Automatisierungsserver

* zB Jenkins
* Vorteile
Völlige Trennung des Testsystems vom aufrufenden System
dadurch können die Ergebnisse kontrolliert werden (i.S.v. tracing)
** Einbindung per RestApi oder durch Hook im Jenkins

== User Stories

* Als neuer Schüler an der HTL Leonding möchte ich unkompliziert,
ohne vorherige Installation einer IDE / Editors einfache (Java-)Programme
ausführen und auch ein Feedback erhalten, um so meine Übungsbeispiele durchführen zu können

* Als neuer Schüler an der HTL Leonding möchte ich unkompliziert,
meine (Java-)Programme die ich in meiner IDE / Editors erstellt habe
auf einem Server abgeben könen und ein Feedback erhalten, ob die Aufgabe richtig gelöst wurde oder nicht ,
um so ohne Lehrer besser lernen zu können

* Als neuer Schüler an der HTL Leonding möchte ich zusätzliche Übungsbeispiele
programmieren können und auch hier sofort Feedback erhalten, um selbstständig üben zu können.